version: "3"
services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: myapp
    command: uvicorn backend.backend_api.api:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - .:/app
    ports:
      - 8000:5000

  db:
    image: postgres
    volumes:
      - fast_api_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=fast_api_db
    ports:
      - "5433:5432"

  test:
    image: myapp
    volumes:
      - .:/app
    command: pytest backend/backend_api/tests/
    depends_on:
      - web

  testwatcher:
    image: myapp
    volumes:
      - .:/app
    command: >
      /bin/bash -c "
      cd backend &&
      poetry run watchmedo shell-command --patterns='*.py' --recursive --command='pytest backend_api/tests/'
      "
    depends_on:
      - web

volumes:
  fast_api_db_data:
